[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/website.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
